'use client';

import { FLAG_SEVERITY_COLOR } from '@/lib/platform/docu/flags';
import type { LineAuditSummary } from '@/lib/platform/docu/line-audit';

/**
 * The extraction-time arithmetic audit, said out loud where the reviewer is
 * already looking (lib/platform/docu/line-audit.ts).
 *
 * Two things it can say, and the difference matters:
 *  - "Columns re-aligned" — the price/amount columns had been read off the wrong
 *    rows and we put them back. The document adds up now, but a human should
 *    glance at it, so this is a warning rather than a quiet success.
 *  - "Line totals do not add up" — the numbers are wrong and nothing could
 *    explain it cleanly, so nothing was changed. The failing rows are named,
 *    because "check this document" without saying where is not help.
 *
 * `note` and the row numbers are generated by our own audit from numbers the
 * model returned — never rendered as HTML.
 */
export function LineAuditNotice({
  audit,
  className = '',
}: {
  audit: LineAuditSummary | null | undefined;
  className?: string;
}) {
  if (!audit?.note) return null;

  const repaired = audit.diagnosis === 'row_shift';
  const c = FLAG_SEVERITY_COLOR[repaired ? 'warning' : 'critical'];
  const title = repaired ? 'Columns re-aligned — worth an eye' : 'Line totals do not add up';

  const rows = repaired ? audit.unresolved_rows : audit.failing_rows;
  const rowsLabel = repaired ? 'Not recovered' : 'Check rows';

  return (
    <div
      className={`rounded-[14px] border px-3.5 py-3 ${className}`}
      style={{ backgroundColor: c.bg, borderColor: c.fg + '33' }}
    >
      <div className="flex items-start gap-2.5">
        <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: c.fg }} />
        <div className="min-w-0">
          <p className="text-[13px] font-semibold" style={{ color: c.fg }}>
            {title}
          </p>
          <p className="mt-0.5 text-[12px] text-[#6B6F68]">{audit.note}</p>
          {rows.length > 0 ? (
            <p className="mt-1 text-[12px] text-[#6B6F68]">
              {rowsLabel}: <span className="of-num font-medium">{rows.join(', ')}</span>
            </p>
          ) : null}
        </div>
      </div>
    </div>
  );
}
