/* Generated by scripts/fetch-logos.mjs from public/integrations/wall/index.json. */
export const WALL_LOGOS: { slug: string; name: string }[] = [
  {
    "slug": "zoom",
    "name": "Zoom"
  },
  {
    "slug": "googledrive",
    "name": "Google Drive"
  },
  {
    "slug": "dropbox",
    "name": "Dropbox"
  },
  {
    "slug": "googlesheets",
    "name": "Google Sheets"
  },
  {
    "slug": "trello",
    "name": "Trello"
  },
  {
    "slug": "asana",
    "name": "Asana"
  },
  {
    "slug": "clickup",
    "name": "ClickUp"
  },
  {
    "slug": "jira",
    "name": "Jira"
  },
  {
    "slug": "hubspot",
    "name": "HubSpot"
  },
  {
    "slug": "zapier",
    "name": "Zapier"
  },
  {
    "slug": "make",
    "name": "Make"
  },
  {
    "slug": "airtable",
    "name": "Airtable"
  },
  {
    "slug": "stripe",
    "name": "Stripe"
  },
  {
    "slug": "paypal",
    "name": "PayPal"
  },
  {
    "slug": "shopify",
    "name": "Shopify"
  },
  {
    "slug": "woocommerce",
    "name": "WooCommerce"
  },
  {
    "slug": "mailchimp",
    "name": "Mailchimp"
  },
  {
    "slug": "zendesk",
    "name": "Zendesk"
  },
  {
    "slug": "intercom",
    "name": "Intercom"
  },
  {
    "slug": "zoho",
    "name": "Zoho"
  },
  {
    "slug": "sap",
    "name": "SAP"
  },
  {
    "slug": "googlegemini",
    "name": "Gemini"
  },
  {
    "slug": "perplexity",
    "name": "Perplexity"
  },
  {
    "slug": "mistralai",
    "name": "Mistral"
  },
  {
    "slug": "huggingface",
    "name": "Hugging Face"
  },
  {
    "slug": "github",
    "name": "GitHub"
  },
  {
    "slug": "gitlab",
    "name": "GitLab"
  },
  {
    "slug": "supabase",
    "name": "Supabase"
  },
  {
    "slug": "postgresql",
    "name": "PostgreSQL"
  },
  {
    "slug": "mysql",
    "name": "MySQL"
  },
  {
    "slug": "googlecloud",
    "name": "Google Cloud"
  },
  {
    "slug": "vercel",
    "name": "Vercel"
  },
  {
    "slug": "cloudflare",
    "name": "Cloudflare"
  },
  {
    "slug": "telegram",
    "name": "Telegram"
  },
  {
    "slug": "discord",
    "name": "Discord"
  },
  {
    "slug": "calendly",
    "name": "Calendly"
  },
  {
    "slug": "typeform",
    "name": "Typeform"
  },
  {
    "slug": "figma",
    "name": "Figma"
  },
  {
    "slug": "evernote",
    "name": "Evernote"
  },
  {
    "slug": "box",
    "name": "Box"
  },
  {
    "slug": "googlecalendar",
    "name": "Google Calendar"
  },
  {
    "slug": "gmail",
    "name": "Gmail"
  },
  {
    "slug": "googlemaps",
    "name": "Google Maps"
  },
  {
    "slug": "basecamp",
    "name": "Basecamp"
  },
  {
    "slug": "miro",
    "name": "Miro"
  },
  {
    "slug": "linear",
    "name": "Linear"
  },
  {
    "slug": "odoo",
    "name": "Odoo"
  },
  {
    "slug": "square",
    "name": "Square"
  },
  {
    "slug": "wise",
    "name": "Wise"
  },
  {
    "slug": "revolut",
    "name": "Revolut"
  },
  {
    "slug": "n8n",
    "name": "n8n"
  },
  {
    "slug": "anthropic",
    "name": "Anthropic"
  },
  {
    "slug": "meta",
    "name": "Meta"
  },
  {
    "slug": "whatsapp",
    "name": "WhatsApp"
  },
  {
    "slug": "xero",
    "name": "Xero"
  },
  {
    "slug": "quickbooks",
    "name": "QuickBooks"
  },
  {
    "slug": "sage",
    "name": "Sage"
  },
  {
    "slug": "notion",
    "name": "Notion"
  },
  {
    "slug": "mongodb",
    "name": "MongoDB"
  },
  {
    "slug": "snowflake",
    "name": "Snowflake"
  },
  {
    "slug": "looker",
    "name": "Looker"
  },
  {
    "slug": "metabase",
    "name": "Metabase"
  },
  {
    "slug": "retool",
    "name": "Retool"
  }
];
